### ISSUE TITLE
failed: ReactiveKafkaIntegrationSpec

### ISSUE THREAD

**Issue by patriknw** [akka/reactive-kafka#107]
https://travis-ci.org/akka/reactive-kafka/builds/115322053

```
[info] - must commit offsets manually *** FAILED ***
[info]   List() did not equal List("3", "4", "5") (ReactiveKafkaIntegrationTestSupport.scala:38)
```

That sleep(3000) is questionable. Why so long, when it's inside a `awaitAssert`?

**Comment by 13h3r** [comment]
Also reproduced from time to time for me

**Comment by kciesielski** [comment]
This tests reads [0,1,2,3,4,5] commits [0,1,2] and then closes the consumer, then opens new consumer connection with *the same groupId* in order to make sure that it reads [3,4,5]. We cannot start new consumer before closing the old one (they have the same groupId), that's why Thread.sleep(3000) is there.
I'm sure this can be written without all these stinky sleeps :)

**Comment by patriknw** [comment]
this issue looks obsolite
