### ISSUE TITLE
Support for Kafka 10.1.x/10.2.x

### ISSUE THREAD

**Issue by kutchar** [akka/reactive-kafka#280]
Kafka 10.1.0 was released back in October 2016 and the current release is Kafka 10.2.0. What are the plans for supporting newer versions of Kafka.

10.1.x introduced a few nice features, including `Time-based Search` and `Time-based Rewind`. It'd be great to get those features into Reactive Kafka.

https://www.confluent.io/blog/announcing-apache-kafka-0-10-1-0/

**Comment by kciesielski** [comment]
@kutchar latest release of akka-stream-kafka (0.14) uses Kafka client 0.10.2, which is compatible with Kafka 0.10.1 https://github.com/akka/reactive-kafka/pulls?utf8=%E2%9C%93&q=is%3Apr%20milestone%3A0.14%20is%3Aclosed%20
Since messages flowing in our streams are of type `org.apache.kafka.clients.consumer.ConsumerRecord[K, V]`, you can read additional fields like timestamp.

**Comment by kutchar** [comment]
@kciesielski Thanks. The `README.md` should probably be updated ;)
